Add simple text formatter
dal-lab/git-sample pull request #3
Opened 2019-01-27 14:39 UTC by angelxtry

The initial version of the text formatter.

2019-01-27 15:37 UTC, ahastudio commented
파이썬 소스 파일은 모듈에 해당합니다. 모듈의 이름 규칙은 `PEP 8`에 명시되어 있습니다.

https://www.python.org/dev/peps/pep-0008/#package-and-module-names

> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.

2019-01-27 15:55 UTC, ahastudio requested changes
PEP 8에 관한 도구로 `pycodestyle`을 추천합니다. https://github.com/PyCQA/pycodestyle

2019-01-27 15:55 UTC, ahastudio commented on SimpleTextFormatter.py
> +    align_sign = {
상수로 쓰인다면 코드 스타일을 통해 드러내는 게 좋습니다.

https://www.python.org/dev/peps/pep-0008/#constants

2019-01-27 15:55 UTC, ahastudio commented on SimpleTextFormatter.py
> +def func_string_template(data_attrs):
함수 이름이 지금보다 훨씬 명확한 게 좋을 것 같습니다. 이름만 봐서는 어떤 건지 짐작하기 어렵네요.

`data`가 어떤 의도로 추가된 건지 불분명합니다. 속성이란 것만 드러내도 충분할 것 같아요.

파이썬에선 이런 용도로 쓰는 함수엔 keyword arguments를 쓰는 편입니다. 일단 사용하는 쪽이 훨씬 깔끔하고 편해요.

2019-01-27 15:55 UTC, ahastudio commented on SimpleTextFormatter.py
> +            align=align_sign.get(data_attrs['ALIGN']),
`ALIGN`이 올바르지 않으면 여기서 `None`이 들어가게 됩니다. 이 경우엔 에러가 발생하게 되죠.
혹시 의도한 게 아니라면 `get`의 두 번째 인자에 기본 값을 넣으시면 도움이 됩니다.

2019-01-27 15:55 UTC, ahastudio commented on SimpleTextFormatter.py
> +    def wrapper(real_data):
함수와 다른 요소는 빈 줄을 하나 넣어서 구분합니다(글로벌에선 두 줄).

2019-01-27 15:55 UTC, ahastudio commented on SimpleTextFormatter.py
> +    func_ID = func_string_template(
특별한 경우가 아니면 함수명은 `snake_case`를 사용합니다.

https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

2019-01-27 15:55 UTC, ahastudio commented on SimpleTextFormatter.py
> +        func_NICK(data_dict.get('NICK'))]
대괄호 오른쪽에 바로 내용이 들어갈 경우 여러 줄이 되면 그 위치를 맞춰줍니다.

https://www.python.org/dev/peps/pep-0008/#indentation

2019-01-27 15:55 UTC, ahastudio commented on SimpleTextFormatter.py
> +        result.append(f'{item}')
하나의 리스트를 다른 리스트로 변환할 땐 list comprehension을 고려해 보세요.

2019-01-28 13:23 UTC, angelxtry commented on SimpleTextFormatter.py
> +    align_sign = {
상수라는 의미를 표시하기 위해 대문자로 변경했습니다.

2019-01-28 13:24 UTC, angelxtry commented on SimpleTextFormatter.py
> +def func_string_template(data_attrs):
명확한 함수명을 고려하지 못했습니다. 좀 더 의도를 드러낼 수 있도록 변경했습니다.

2019-01-28 13:25 UTC, angelxtry commented on SimpleTextFormatter.py
> +            align=align_sign.get(data_attrs['ALIGN']),
전혀 고려하지 못한 부분이네요. 좋은 지적 고맙습니다!

2019-01-28 13:25 UTC, angelxtry commented on SimpleTextFormatter.py
> +    def wrapper(real_data):
앞으로 pep8을 신경쓰면서 작성하겠습니다~

2019-01-28 16:32 UTC, ahastudio approved these changes
:+1:

2019-01-28 16:37 UTC, ahastudio commented
다른 Pull Request에서 `pytest`나 `doctest`를 써서 테스트 및 문서화를 잡아주면 좋을 것 같아요.

- https://pytest.org/
- https://docs.python.org/3/library/doctest.html

2019-01-29 11:54 UTC, merged

2019-01-29 18:19 UTC, ahastudio commented
`git reabse -i HEAD~2`로 커밋을 하나로 정리해서 합치면 나중에 커밋 로그를 추적할 때 훨씬 깔끔한 최종 결과만 볼 수 있습니다.